In [ ]:
import numpy as np

# a+2b+3c+4d = 30
# f(x) = a+2b+3c+4d - 30

# Inisialisasi Jumlah Populasi
n = 6 

# Pembentukan Chromosome
chromosome = np.random.randint(0, 30,(n,4))
print("Chromosome :", chromosome)

Chromosome : [[14  7 28  7]
 [11 12 23  7]
 [ 0 26 27 24]
 [14 10 10 23]
 [ 1  1  6 22]
 [18  6 27 15]]


In [ ]:
epoch = 0
  while epoch < 200 :
      # Evaluasi Chromosome
        fungsi_objektif = abs(chromosome[:,0] + 2*chromosome[:,1] + 3*chromosome[:,2] + 4*chromosome[:,3] - 30 )
        print("----------------------")
        print("Fungsi Objektif : ", fungsi_objektif)

      # Seleksi Chromosome
        fitness =  1/(1 + fungsi_objektif)
        print("Fitness : ", fitness)
      
      # Total dari fitness
        total = fitness.sum()
        print("Total : ", total)
      
      # Mencari probabilitas
        P = fitness/total
        print("Probabilitas : ", P)
      
      # seleksi kita gunakan roulete wheel, untuk itu kita harus mencari dahulu nilai kumulatif probabilitasnya
        C = np.cumsum(P)
        print("Nilai Kumulatif probabilitas : ", C)
      
      # membangkitkan bilangan acak R dalam range 0-1
        Acak = np.random.random((chromosome.shape[0]))
        print("R :",Acak)
      
      # Membuat matrix baru Chromosome
        chromosome_2 = np.zeros((chromosome.shape[0],4))
        
        for i in range(Acak.shape[0]):
            for j in range(chromosome.shape[0]):
                if Acak[i]  < C[j]:
                    chromosome_2[i,:] = chromosome[j,:]
                    break
                
        chromosome = chromosome_2
        print("Chromosome Setelah di Perbarui :",chromosome)
          
      # Crossover

      # bangkitkan bilangan acak R sebanyak jumlah populasi
        R = [np.random.random() for i in range(n)]
        print("Nilai Random :",R)
      
      # tentukan crossover probability adalah sebesar 25%
        pc = 0.25

      # Chromosome ke k akan dipilih sebagai induk jika R[k] < ρc
        flag = Acak < pc
        print("Nilai flag :",flag)
      
      # menentukan posisi crossover
        cross_chromosome = chromosome[[(i == True) for i in flag]]
        print("Cross chromosome :",cross_chromosome)
        len_cross_chrom = len(cross_chromosome)
      
      # bilangan acak yang dibangkitkan adalah 1 – 3
        cross_values = np.random.randint(1,3,len_cross_chrom)
        print("C :",cross_values)
      
      # Copy nilai chromosome untuk dilakukan perhitungan
        copy_chromosome = np.zeros(cross_chromosome.shape)
        for i in range(cross_chromosome.shape[0]):
        copy_chromosome[i , :] = cross_chromosome[i , :]
          if len_cross_chrom == 1:
              cross_chromosome = cross_chromosome
          else :
              for i in range(len_cross_chrom):
                  c_val = cross_values[i]
                  if i == len_cross_chrom - 1 :
                      cross_chromosome[i , c_val:] = copy_chromosome[0 , c_val:]
                  else :
                  cross_chromosome[i , c_val:] = copy_chromosome[i+1 , c_val:]
              
                  print("Crossover Chromosome :",cross_chromosome)
          
          index_chromosome = 0
          index_chromosomebaru = 0
          for i in flag :
              if i == True :
                  chromosome[index_chromosome, :] = cross_chromosome[index_chromosomebaru, :]
                  index_chromosomebaru = index_chromosomebaru + 1
                  index_chromosome = index_chromosome + 1 
        
                  print("Chromosome Baru :", chromosome)
      

      # Mutasi
        a ,b = chromosome.shape[0] ,chromosome.shape[1]
        total_gen = a*b
        print("Total generasi :",total_gen)
      
      # mutation rate (pm)
        pm = 0.1
        jumlah_mutasi = int(np.round(pm * total_gen))
        print("Jumlah Mutasi :" ,jumlah_mutasi)
      
      # Generate angka acak
        gen_num = np.random.randint(0,total_gen - 1, jumlah_mutasi)
        print(" Generate Angka Acak : " , gen_num)
      
      # nilai gen pada posisi tersebut kita ganti dengan bilangan acak 0-30
        Ganti_angka = np.random.randint(0,30, jumlah_mutasi)
        print("Nomor yang akan diganti : " , Ganti_angka)
        
          for i in range(jumlah_mutasi):
              a = gen_num[i]
              baris = a//4
              kolom = a%4
              chromosome[baris , kolom] = Ganti_angka[i]
          
          print(" Chromosome Setelah di Mutasi : " , chromosome)
        
          epoch = epoch + 1

Streaming output truncated to the last 5000 lines.
Nilai Kumulatif probabilitas : [0.00768246 0.24583867 0.48399488 0.52368758 0.76184379 1.        ]
R : [0.5346473  0.39930244 0.81324275 0.31494064 0.36028388 0.87043607]
Chromosome setelah di perbarui : [[1. 3. 5. 2.]
 [1. 3. 5. 2.]
 [1. 3. 5. 2.]
 [1. 3. 5. 2.]
 [1. 3. 5. 2.]
 [1. 3. 5. 2.]]
Nilai Random : [0.5549364002269999, 0.3811801999170523, 0.9223670099213205, 0.09354184652591102, 0.14225013346440196, 0.56415995030281]
Nilai flag : [False False False False False False]
Cross chromosome : []
Nilai Cross : []
Crossover Chromosome : []
Chromosome Baru : [[1. 3. 5. 2.]
 [1. 3. 5. 2.]
 [1. 3. 5. 2.]
 [1. 3. 5. 2.]
 [1. 3. 5. 2.]
 [1. 3. 5. 2.]]
Total generasi : 24
Jumlah Mutasi : 2
 Generate Angka Acak :  [ 2 12]
 Nomor yang akan diganti :  [26  8]
 Chromosome Setelah di Mutasi :  [[ 1.  3. 26.  2.]
 [ 1.  3.  5.  2.]
 [ 1.  3.  5.  2.]
 [ 8.  3.  5.  2.]
 [ 1.  3.  5.  2.]
 [ 1.  3.  5.  2.]]
----------------------
Fungsi Objektif 